// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import MarkdownViewerController from "./markdown_viewer_controller"
import TextareaAutogrow from 'stimulus-textarea-autogrow'
import ToastController from "./toast_controller"

application.register("markdown-viewer", MarkdownViewerController)
application.register("textarea-autogrow", TextareaAutogrow)
application.register("toast", ToastController)
