// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import MarkdownViewerController from "./markdown_viewer_controller"
import Pwa__WebPushSubscriptionController from "./pwa/web_push_subscription_controller"
import SlimSelectController from "./slim_select_controller"
import TaskElapsedTimeUpdaterController from "./task_elapsed_time_updater_controller"
import TextareaAutoResizeController from "./textarea_auto_resize_controller"
import ToastController from "./toast_controller"

application.register("markdown-viewer", MarkdownViewerController)
application.register("pwa--web-push-subscription", Pwa__WebPushSubscriptionController)
application.register("slim-select", SlimSelectController)
application.register("task-elapsed-time-updater", TaskElapsedTimeUpdaterController)
application.register("textarea-auto-resize", TextareaAutoResizeController)
application.register("toast", ToastController)
